export const upcomingTrips = [
  {
    id: 1,
    driver: "John Doe",
    driverImage: "/images/ProfilePic.jpg",
    driverName: "John Doe",
    driverRating: 4.8,
    origin: "New York",
    destination: "Boston",
    date: "2023-06-15",
    price: 45,
    pickupTime: "09:00 AM",
    dropoffTime: "12:00 PM",
    carYear: 2019,
    carModel: "Toyota Camry",
  },
  {
    id: 2,
    driver: "Jane Smith",
    driverImage: "/images/ProfilePic.jpg",
    driverName: "Jane Smith",
    driverRating: 4.9,
    origin: "Los Angeles",
    destination: "San Francisco",
    date: "2023-06-16",
    price: 60,
    pickupTime: "08:30 AM",
    dropoffTime: "12:30 PM",
    carYear: 2021,
    carModel: "Honda Accord",
  },
  {
    id: 3,
    driver: "Bob Johnson",
    driverImage: "/images/ProfilePic.jpg",
    driverName: "Bob Johnson",
    driverRating: 4.7,
    origin: "Chicago",
    destination: "Detroit",
    date: "2023-06-17",
    price: 40,
    pickupTime: "10:00 AM",
    dropoffTime: "01:30 PM",
    carYear: 2018,
    carModel: "Ford Fusion",
  },
];
