import { Car } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className="min-h-screen overflow-hidden">
      <div className="p-8">
        <Link href="/">
          <span className="ml-4 inline-block animate-bounce text-teal-400">
            <Car className="h-12 w-12 transform rotate-12" />
          </span>
        </Link>
      </div>

      {children}
    </div>
  );
}
