import { CarFront } from "lucide-react";
import Link from "next/link";
import MetaButton from "@/components/metamask/MetaButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div>
      <header className="sticky top-0 z-50 w-full bg-teal-500 shadow-md ">
        <div className="container mx-auto flex h-16 items-center justify-center px-4">
          <Link href="/" className="flex items-center space-x-2">
            <h1 className="flex items-center text-2xl font-bold text-white font-yeseva">
              CarHop
              <span className="ml-2 inline-block animate-bounce">
                <CarFront className="h-6 w-6 transform rotate-12" />
              </span>
            </h1>
          </Link>
        </div>
      </header>

      <MetaButton />
      <div className="py-6">{children}</div>
    </div>
  );
}
